.TH FMVCMD 1 "Jan 2005" FSP
.SH NAME
fmv, fmvcmd \- rename files on the FSP server
.SH SYNOPSIS
.B fmvcmd
.I oldfile newfile
.SH DESCRIPTION
.LP
This command renames file on FSP server. 
.LP
You can use wildcard
for matching oldfile name. This wilcard must not be expanded into
more than one file name by FSP server.
    
.SH ENVIRONMENT
.LP
See fsp_env(7) for list of used environment variables.
.SH "SEE ALSO"
.PD
fcatcmd(1), fcdcmd(1), fgetcmd(1), fgrabcmd(1), flscmd(1), fmkdir(1),
fprocmd(1), fput(1), frmcmd(1), frmdircmd(1), fver(1), fducmd(1),
fhostcmd(1), fspd(1), fsp_prof(5), ffindcmd(1), fsp_env(7), fbye(1)
