.TH FPUT 1 "9 Sep 2003" FSP
.SH NAME
fput \- upload files to the FSP server
.SH SYNOPSIS
.B fput
[ -p ]
.I filename
\&.\|.\|.
.SH DESCRIPTION
.LP
When used without arguments, a list of file names is read from the
standard input.  When arguments are given, the arguments are taken
to be the list of file names.  For each file named in the list,
.B fput
copies the file from the client's current working directory in the
client machine to the FSP database.
.SH ARGUMENTS
.B -p
-- preserve date/time of original file.
.SH ENVIRONMENT
.LP
See fsp_env(7) for list of used environment variables.
.SH "SEE ALSO"
.PD
fcatcmd(1), fcdcmd(1), fgetcmd(1), fgrabcmd(1), flscmd(1), fmkdir(1),
fprocmd(1), fput(1), frmcmd(1), frmdircmd(1), fver(1), fducmd(1),
fhostcmd(1), fspd(1), fsp_prof(5), ffindcmd(1), fsp_env(7)
