.TH FVER 1 "Dec 2004" FSP
.SH NAME
fver \- displays the version number string of the FSP database
.SH SYNOPSIS
.B fver
.I [-l]
.SH DESCRIPTION
.LP
Without arguments,
.B fver
displays the version string of the remote FSP server.
Otherwise, the version string of the client utilities and
compile time options are displayed.
.SH ENVIRONMENT
.LP
See fsp_env(7) for list of used environment variables.
.SH "SEE ALSO"
.PD
fcatcmd(1), fcdcmd(1), fgetcmd(1), fgrabcmd(1), flscmd(1), fmkdir(1),
fprocmd(1), fput(1), frmcmd(1), frmdircmd(1), fver(1), fducmd(1), 
fhostcmd(1), fspd(1), fsp_prof(5), ffindcmd(1), fsp_env(7)
